spring.application.name=TeamPixeltek
# Indirizzo del database (cambia 'nome_del_tuo_db' con quello reale)
spring.datasource.url=jdbc:mysql://localhost:3306/teampixeltek_db
spring.datasource.username=root
spring.datasource.password=root

# Driver MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Regole per Hibernate (opzionale, utile per creare/aggiornare le tabelle in automatico)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false